<section class="user">
    <form method="post" action="/user">
        <h3 class="title">Login</h3>

        <input class="input" name="username" type="text" placeholder="Usuário">

        <input class="input" name="senha" type="password" placeholder="Senha">

        <?php if(isset($_GET['erro']) && $_GET['erro'] == 1) { ?>

            <p>Usuario ou senha invalidos</p>

        <?php } ?>

        <button class="btn__input" type="submit">Entrar</button>
    </form>
</section>