<section class="center-xy user">
    <h3 class="title">Login</h3>
    
    <form method="post" action="/user">

        <input class="input" name="username" type="text" placeholder="Usuário">

        <input class="input" name="senha" type="password" placeholder="Senha">

        <?php if(isset($_GET['erro']) && $_GET['erro'] == 1) { ?>

            <p class="text-red">Usuario ou senha invalidos</p>

        <?php } ?>

        <button class="btn__input" type="submit">Entrar</button>
    </form>
</section>