<?php

if(!isset($_SESSION['autenticado']) && $_SESSION['autenticado'] != true) {
    header('Location: /');
}

$now = time();
if (isset($_SESSION['discard_after']) && $now > $_SESSION['discard_after']) {
    // this session has worn out its welcome; kill it and start a brand new one
    session_unset();
    session_destroy();
}

// either new or old, it should live at most for another hour
$_SESSION['discard_after'] = $now + (3600 * 16);

?>

<section class="texto">
    <a class="btn__back--home" href="/logout"></a>

    <h1 class="text-size align-center px-10"><?= $this->view->texto ?></h1>

    <div class="mt-5 align-center px-10">
        <ul class="notas">
            <li><button class="btn btn__avalia-1">1</button></li>
            <li><button class="btn btn__avalia-2">2</button></li>
            <li><button class="btn btn__avalia-3">3</button></li>
            <li><button class="btn btn__avalia-4">4</button></li>
            <li><button class="btn btn__avalia-5">5</button></li>
            <li><button class="btn btn__avalia-6">6</button></li>
            <li><button class="btn btn__avalia-7">7</button></li>
            <li><button class="btn btn__avalia-8">8</button></li>
            <li><button class="btn btn__avalia-9">9</button></li>
            <li><button class="btn btn__avalia-10">10</button></li>
        </ul>
    </div>
</section>