<?php

if(!isset($_SESSION['autenticado']) && $_SESSION['autenticado'] != true || $_SESSION['permissao'] != 'adm') {
    header('Location: /');
}

?>

<a class="btn__back" href="/menu">Menu</a>

<?php if(isset($_GET['sucesso']) && $_GET['sucesso'] == 1) { ?>
    <div class="sucess">Usuário registrado com sucesso!</div>
<?php } ?>

<section class="center-xy user">
    
    <form method="post" action="/user-create">
        <input class="input" type="text" name="username" placeholder="Usuario" required minlength="3" value="<?php if(isset($_GET['username'])) print $_GET['username'] ?>">
        <input class="input" type="password" name="senha" placeholder="Senha" required minlength="3">
        <input class="input" type="password" name="confirma" placeholder="Confirme a senha" required minlength="3">

        <?php if(isset($_GET['erro']) && $_GET['erro'] == 1) { ?>
            <div class="text-red">Senhas incompatíveis</div>
        <?php } ?>

        

        <button class="btn__input" type="submit">Registrar</button>
    </form>
</section>