<html>
	<head>
		<meta charset="utf-8" />
		<title>Aplicação web da Hórus para avaliação de satisfação</title>
		<meta name="author" content="Marcos de Oliveira">
		<meta name="description" content="Aplicativo para o bar/restaurante Hórus, para avaliação de clientes com base no sistema nps.">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">	
			
		<link rel="stylesheet" type="text/css" href="src/css/main.css?version=1.6">        

		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		crossorigin="anonymous"></script>

		<script src="src/js/btn-avaliacao.js"></script>
	</head>

	<body class="page">
		<div><img class="logo" src="src/img/horus-logo.svg"></div>

		<?= $this->content() ?>
	</body>

</html>