<?php

require_once "App/Config.php";

?>

<a class="btn__back" href="/logout">Sair</a>

<section class="nps">
    <div class="nps__box align-center">
        <a class="btn__input" href="/nps-dia?data=<?= $date->format('Y-m-d') ?>">Nps do dia</a>
        <a class="btn__input" href="/nps-mes?data=<?= $date->format('Y-m') ?>">Nps do mês</a>    
        <a class="btn__input" href="/nps-ano?data=<?= $date->format('Y') ?>">Nps do ano</a> 
        <a class="btn__input" href="/register">Registrar Usuário</a>    
        <a class="btn__input" href="/texto-edit">Alterar Textos</a>   
    </div>

    <div class="nps__box">
        
        <!-- Nps do mês -->
        <div>
            <div class="grid grid--gap">
                <div class="nps__search">
                    <form method="post" action="/nps-mes">
                        <input class="input" type="month" name="data" max="<?= $date->format('Y-m'); ?>" value="<?php
                            if(isset($this->view->data) && !empty($this->view->data)) echo $this->view->data; else echo $date->format('Y-m'); 
                        ?>">
                
                        <button class="btn__input nps__btn" type="submit">Consultar</button>
                    </form>
                </div>
                
                <?php if(isset($this->view->npsMes) && !empty($this->view->npsMes)) { ?>

                    <div class="grafico">
                        <div class="grafico__dados">
                            <span class="grafico__text">% de promotores</span>
                            <div class="grafico__box grafico__box--bg-promo">
                                <span class="center-xy"><?= $this->view->npsMes['promoters_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">% de neutros</span>
                            <div class="grafico__box grafico__box--bg-neutro">
                                <span class="center-xy"><?= $this->view->npsMes['passives_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">% de detratores</span>
                            <div class="grafico__box grafico__box--bg-detra">
                                <span class="center-xy"><?= $this->view->npsMes['detrators_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de promotores</span>
                            <div class="grafico__box grafico__box--bg-promo">
                                <span class="center-xy"><?= $this->view->npsMes['promoters'] ?></span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de neutros</span>
                            <div class="grafico__box grafico__box--bg-neutro">
                                <span class="center-xy"><?= $this->view->npsMes['passives'] ?></span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de detratores</span>
                            <div class="grafico__box grafico__box--bg-detra">
                                <span class="center-xy"><?= $this->view->npsMes['detrators'] ?></span>
                            </div>
                        </div>
                        
                        <div class="grafico__dados">
                            <div class="grafico__box" style="background-color:<?= $this->view->npsColor ?>">
                                <span class="center-xy">nps: <?= $this->view->npsMes['nps_total'] ?></span>
                            </div>
                        </div>
                        
                        <div class="grafico__dados">
                            <div class="evolucao evolucao__total">
                                <h2 class="evolucao__title evolucao__title--sm">Grafico de nps mensal</h2>

                                <div class="evolucao__guia evolucao__guia--sm">
                                    <p class="evolucao__text evolucao__text--sm"><span class="evolucao--bg-detrator"></span>Detratores</p>
                                    <p class="evolucao__text evolucao__text--sm"><span class="evolucao--bg-passive"></span>Passivos</p>
                                    <p class="evolucao__text evolucao__text--sm"><span class="evolucao--bg-promotor"></span>Promotores</p>
                                </div>

                                <div class="evolucao__inner evolucao__inner--sm">
                                    <div class="evolucao__grafico--nps">
                                        <div class="evolucao--bg-detrator" style="height: <?= $this->view->npsMes['detrators_porc'] . "%" ?> "></div>
                                    </div>

                                    <div class="evolucao__grafico--nps">
                                        <div class="evolucao--bg-passive" style="height: <?= $this->view->npsMes['passives_porc'] . "%" ?> "></div>
                                    </div>

                                    <div class="evolucao__grafico--nps">
                                        <div class="evolucao--bg-promotor" style="height: <?= $this->view->npsMes['promoters_porc'] . "%" ?> "></div>
                                    </div>

                                </div>
                            </div>
                        </div>   
                    </div>

                    <div class="evolucao">
                        <h2 class="evolucao__title">Grafico de evolução mensal em %</h2>

                        <div class="evolucao__guia">
                            <p class="evolucao__text"><span class="evolucao--bg-detrator"></span>Detratores</p>
                            <p class="evolucao__text"><span class="evolucao--bg-passive"></span>Passivos</p>
                            <p class="evolucao__text"><span class="evolucao--bg-promotor"></span>Promotores</p>
                        </div>

                        <div class="evolucao__inner">

                            <?php foreach($this->view->graficoMensal as $graficoMensal) { ?>

                                <div class="evolucao__grafico">
                                    <div class="evolucao--bg-promotor" style="height: <?= $graficoMensal['promoters_porc'] . "%" ?> "></div>
                                    <div class="evolucao--bg-passive" style="height: <?= $graficoMensal['passives_porc'] . "%" ?> "></div>
                                    <div class="evolucao--bg-detrator" style="height: <?= $graficoMensal['detrators_porc'] . "%" ?> "></div>
                                    <div class="evolucao__data"><?= $graficoMensal['data']?></div>
                                </div>

                            <?php } ?>

                        </div>
                    </div>

                    <div class="evolucao">
                        <h2 class="evolucao__title">Grafico de evolução mensal do Nps</h2>

                        <div class="evolucao__guia">
                            <p class="evolucao__text"><span class="evolucao--bg-nps"></span>Nps mês a mês</p>
                        </div>

                        <div class="evolucao__inner evolucao__inner--nps">

                            <div class="evolucao__nps-line">100</div>
                            <div class="evolucao__nps-line evolucao__nps-line--75">75</div>
                            <div class="evolucao__nps-line evolucao__nps-line--50">50</div>
                            <div class="evolucao__nps-line evolucao__nps-line--25">25</div>
                            <div class="evolucao__nps-line evolucao__nps-line--0">0</div>

                            <?php foreach($this->view->graficoMensal as $graficoMensal) { ?>

                                <div class="evolucao__grafico--nps">
                                    <div class="evolucao--bg-nps" style="height: <?= $graficoMensal['nps_total'] . "%" ?> "></div>
                                    <div class="evolucao__data evolucao__data--nps"><?= $graficoMensal['data']?></div>
                                </div>

                            <?php } ?>                            

                        </div>
                    </div>

                <?php } ?>

                <?php if(!isset($this->view->npsMes) && empty($this->view->npsMes)) { ?>

                    <h3 class="align-center mt-5">Não existe nenhuma avaliação para essa data.</h3>

                <?php } ?>
            </div>
        </div>
        
    </div>

</section>