<?php

if(!isset($_SESSION['autenticado']) && $_SESSION['autenticado'] != true || $_SESSION['permissao'] != 'adm') {
    header('Location: /logout');
}

$years = range(2020, strftime("%Y", time()));

$timeZone = new DateTimeZone('America/Sao_Paulo');

$date = new DateTime('now', $timeZone);

?>

<a class="btn__back" href="/logout">Sair</a>

<section class="nps">
    <div class="nps__box align-center">
        <a class="btn__input" href="/nps-dia?data=<?= $date->format('Y-m-d') ?>">Nps do dia</a>
        <a class="btn__input" href="/nps-mes?data=<?= $date->format('Y-m') ?>">Nps do mês</a>    
        <a class="btn__input" href="/nps-ano?data=<?= $date->format('Y') ?>">Nps do ano</a> 
        <a class="btn__input" href="/register">Registrar Usuário</a>    
        <a class="btn__input" href="/texto-edit">Alterar Textos</a>    
    </div>

    <div class="nps__box">
        
        <!-- Nps do ano -->
        <div>
            <div class="grid grid--gap">
                <div class="nps__search">
                    <form method="post" action="/nps-ano">
                        <select class="input" name="data">
                            <?php foreach($years as $year) { ?>
                                <option value="<?= $year ?>"><?= $year ?></option>
                            <?php } ?>
                        </select>

                        <button class="btn__input nps__btn" type="submit">Consultar</button>
                    </form>
                </div>

                <?php if(isset($this->view->npsAno) && !empty($this->view->npsAno)) { ?>
                    <div class="grafico">
                        <div class="grafico__dados">
                            <span class="grafico__text">% de promotores</span>
                            <div class="grafico__box grafico__box--bg-promo">
                                <span class="center-xy"><?= $this->view->npsAno['promoters_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">% de neutros</span>
                            <div class="grafico__box grafico__box--bg-neutro">
                                <span class="center-xy"><?= $this->view->npsAno['passives_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">% de detratores</span>
                            <div class="grafico__box grafico__box--bg-detra">
                                <span class="center-xy"><?= $this->view->npsAno['detrators_porc'] ?>%</span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de promotores</span>
                            <div class="grafico__box grafico__box--bg-promo">
                                <span class="center-xy"><?= $this->view->npsAno['promoters'] ?></span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de neutros</span>
                            <div class="grafico__box grafico__box--bg-neutro">
                                <span class="center-xy"><?= $this->view->npsAno['passives'] ?></span>
                            </div>
                        </div>

                        <div class="grafico__dados">
                            <span class="grafico__text">Quantidade de detratores</span>
                            <div class="grafico__box grafico__box--bg-detra">
                                <span class="center-xy"><?= $this->view->npsAno['detrators'] ?></span>
                            </div>
                        </div>
                        
                        <div class="grafico__dados">
                            <div class="grafico__box" style="background-color:<?php 
                                    if($this->view->npsAno['nps_total'] > 75) 
                                        echo "#1FB257";
                                    else if($this->view->npsAno['nps_total'] >= 40 && $this->view->npsAno['nps_total'] <= 75)
                                        echo "#0089CD";
                                    else if($this->view->npsAno['nps_total'] <= 0)
                                        echo "#F62119";
                                    else echo "#E7BA28";
                                ?>">
                                <span class="center-xy">nps: <?= $this->view->npsAno['nps_total'] ?>%</span>
                            </div>
                        </div>

                        
                        <div class="grafico__dados">
                            <div class="grafico__circle">
                                <div class="grafico__inside"><div class="center-xy"></div></div>

                                <div id="porcion1" class="grafico__recorte">
                                    <div class="grafico__quesito"></div>
                                </div>

                                <div id="porcion2" class="grafico__recorte">
                                    <div class="grafico__quesito"></div>
                                </div>

                                <div id="porcion3" class="grafico__recorte">
                                    <div class="grafico__quesito"></div>
                                </div>
                            </div>
                        </div>   
                    </div>
                <?php } ?>

                <?php if(!isset($this->view->npsAno) && empty($this->view->npsAno)) { ?>
                    <h3 class="mt-5">Não existe nenhuma avaliação para essa data.</h3>
                <?php } ?>
            </div>
        </div>
        
    </div>

</section>

<!-- <script src="src/js/consulta.js"></script> -->